/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.HoadonDAO;
import DAO.LinhkienDAO;
import GUI.GuiControl.TablemodelBanhang_ctHoadon;
import GUI.GuiControl.TablemodelBanhang_linhkien;
import GUI.GuiControl.Tablemodelformhoadon;
import entities.CT_hoadon;
import entities.Hoadon;
import entities.Linhkien;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.layout.Border;
import javax.swing.JFrame;

/**
 *
 * @author Ke Hien Le
 */
public class formnhaptienkhachhangdua extends javax.swing.JFrame {

    private List<CT_hoadon> giohang;
    private Frame frame;
     private int soluong;
    private float giamgia;
    private Hoadon hoadon;
    private Linhkien linhkien;
    private  int tienkhachdua;

    public List<CT_hoadon> getGiohang() {
        return giohang;
    }

    public void setGiohang(List<CT_hoadon> giohang) {
        this.giohang = giohang;
    }

    public Frame getFrame() {
        return frame;
    }

    public void setFrame(Frame frame) {
        this.frame = frame;
    }

    
    
    public Hoadon getHoadon() {
        return hoadon;
    }

    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }

    public Linhkien getLinhkien() {
        return linhkien;
    }

    public void setLinhkien(Linhkien linhkien) {
        this.linhkien = linhkien;
    }

   
    public int getSoluong() {
        return soluong;
    }

    public float getGiamgia() {
        return giamgia;
    }

    public void setGiamgia(float giamgia) {
        this.giamgia = giamgia;
    }

    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    
    /**
     * Creates new form formdanhmuc
     */
    public formnhaptienkhachhangdua(List<CT_hoadon> giohang) {
        initComponents();
        this.giohang=giohang;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_thongbao = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        txt_sotienkhachdua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImages(null);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_thongbao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_thongbao.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(lb_thongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 51, 153));
        jLabel58.setText("Số tiền khách hàng đưa");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 270, 50));

        jButton12.setBackground(new java.awt.Color(0, 153, 51));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Tiếp tục");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton12.setBorderPainted(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 300, 40));

        jButton13.setBackground(new java.awt.Color(153, 0, 51));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Trở lại");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 50));

        txt_sotienkhachdua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sotienkhachduaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_sotienkhachdua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 
        double sl = Double.valueOf(frame.getjLabel40().getText().replaceAll(",", ""));

        try {
            tienkhachdua = Integer.parseInt(txt_sotienkhachdua.getText());

        } catch (Exception e) {

            jLabel2.setText("Chỉ được nhập số > 0");
            return;

        }

        if (0 > tienkhachdua) {
            jLabel2.setText("Số tiền không được âm");
            return;
        }

        if (sl > tienkhachdua) {
            jLabel2.setText("Không đủ tiền");
            return;
        } else {
            HoadonDAO hddao = new HoadonDAO(Hoadon.class);
            LinhkienDAO lkdaox = new LinhkienDAO(Linhkien.class);
            frame.getHd().setTienkhachhangdua(tienkhachdua);
            
            hddao.savewithorder(frame.getHd());
            for (CT_hoadon x : frame.getHd().getDsCthd()) {
                Linhkien lk = lkdaox.findById(x.getLinhkien().getId());
                lk.setSoluong(lk.getSoluong()-x.getSoluong());
                            lkdaox.update(lk);
            }
            // clear all
            
            
                Formhoadon fr = new Formhoadon(frame.getHd(), frame);
                
                
               
    //        fr.setHd();
            fr.setTiendua(tienkhachdua);
            fr.setthongtin();

         
        
            fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            fr.setLocationRelativeTo(this);
            fr.setVisible(true);// TODO add your handling code here:
            fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            fr.setLocationRelativeTo(this);
            

            this.setEnabled(false);

            fr.show();
            fr.setResizable(false);
            fr.setAlwaysOnTop(true);
            fr.pack();
            this.dispose();
            fr.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    setEnabled(true);
                    setAlwaysOnTop(true);
                    
                }
            });

            giohang.clear();
            frame.getModelgiohang().setData(giohang);
            frame.getModelgiohang().fireTableDataChanged();

            List<Linhkien> databh_lk = frame.getDatabanhang_linhkien();
            LinhkienDAO lkdao = new LinhkienDAO(Linhkien.class);
            databh_lk = lkdao.findAll();
            frame.getModelbanhang_linhkien().setData(databh_lk);
            frame.getjTable10().setModel(frame.getModelbanhang_linhkien());
            frame.getModelbanhang_linhkien().fireTableDataChanged();
        

       
       }
 

              
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txt_sotienkhachduaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sotienkhachduaKeyReleased
       
        if(txt_sotienkhachdua.getText().length()>9)
        {
            txt_sotienkhachdua.setText(txt_sotienkhachdua.getText().substring(0,9));
            lb_thongbao.setText("Số tiền không hợp lệ");
        }
            
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            txt_sotienkhachdua.setEditable(true);
            lb_thongbao.setText("");
        }
        else{
            txt_sotienkhachdua.setEditable(false);
            lb_thongbao.setText("Không nhập chữ và kí tự lạ");
        }
        lb_thongbao.setText("");
    }//GEN-LAST:event_txt_sotienkhachduaKeyReleased

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_thongbao;
    private javax.swing.JTextField txt_sotienkhachdua;
    // End of variables declaration//GEN-END:variables
}
