/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import entities.CT_hoadon;
import entities.Hoadon;
import entities.Linhkien;
import java.awt.event.KeyEvent;
import java.util.List;
import javafx.scene.layout.Border;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Ke Hien Le
 */
public class formnhapsl extends javax.swing.JFrame {

    private List<CT_hoadon> giohang;
    private Frame frame;
    private int soluong;
    private Hoadon hoadon;
    private Linhkien linhkien;

    public List<CT_hoadon> getGiohang() {
        return giohang;
    }

    public void setGiohang(List<CT_hoadon> giohang) {
        this.giohang = giohang;
    }

    public Frame getFrame() {
        return frame;
    }

    public void setFrame(Frame frame) {
        this.frame = frame;
    }

    public Hoadon getHoadon() {
        return hoadon;
    }

    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }

    public Linhkien getLinhkien() {
        return linhkien;
    }

    public void setLinhkien(Linhkien linhkien) {
        this.linhkien = linhkien;
    }

    public int getSoluong() {
        return soluong;
    }

    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }

    /**
     * Creates new form formdanhmuc
     */
    public formnhapsl(List<CT_hoadon> giohang) {
        initComponents();
        this.giohang = giohang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        lb_thongbao = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        txt_soluong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImages(null);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 130, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 51, 153));
        jLabel58.setText("Số lượng");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 50));

        jButton12.setBackground(new java.awt.Color(0, 153, 51));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Tiếp tục");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton12.setBorderPainted(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 50));

        lb_thongbao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_thongbao.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lb_thongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 280, 40));

        jButton13.setBackground(new java.awt.Color(153, 0, 51));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Trở lại");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 50));

        txt_soluong.setText("1");
        txt_soluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soluongKeyReleased(evt);
            }
        });
        jPanel1.add(txt_soluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, 40));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_chevron_up_filled_10px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_chevron_down_filled_10px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int kq = 0, sl = 0;
        try {
            sl = Integer.parseInt(txt_soluong.getText());
            this.soluong = sl;
        } catch (NumberFormatException e) {

            kq = 1;
        }

            // code block
        
        if (this.linhkien.getSoluong() < this.soluong) // ver Ke_hien
        {
            lb_thongbao.setText("Không đủ số lượng");

            return;
        }
        if (0 > this.soluong) {
            lb_thongbao.setText("Số lượng không được âm");

            return;
        }
        if (!(kq == 1 || sl == 0)) {
            this.dispose();
        } else if (sl == 0) {
            lb_thongbao.setText("Số lượng >=1");
            return;
        } else if (kq == 1) {
            lb_thongbao.setText("Chỉ chấp nhận kí tự số");
            return;
        }
            for (CT_hoadon ct : frame.getGiohang()) {
            if(ct.getLinhkien().getId().equals(frame.getjLabel103().getText().trim()))
            {
               int qq= ct.getSoluong();
              if(qq+sl > ct.getLinhkien().getSoluong())
              {
                  JOptionPane.showMessageDialog(this, "Không đủ số lượng");
                  return;
              }
                ct.setSoluong(sl+qq);
                frame.getModelgiohang().fireTableDataChanged();
                frame.getModelbanhang_linhkien().fireTableDataChanged();
                return ;
            }
        }
        this.hoadon = frame.getHd();
        hoadon.setNhanvien(frame.getNhanvien());
        giohang.add(new CT_hoadon(this.hoadon, this.linhkien, this.soluong));
        frame.getjTable11().setModel(frame.getModelgiohang());
       // frame.getModelbanhang_linhkien().getData().remove(this.linhkien);
       // frame.getDatabanhang_linhkien().remove(this.linhkien);
        frame.getModelgiohang().fireTableDataChanged();
        frame.getModelbanhang_linhkien().fireTableDataChanged();
        frame.getjTable10().clearSelection();
        frame.getjLabel40().setText(frame.formattien(this.hoadon.Tinhtien()));


    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txt_soluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soluongKeyReleased
        // TODO add your handling code here:
        String key = txt_soluong.getText();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_soluong.setEditable(true);
            lb_thongbao.setText("");
            try {
                int sl = Integer.parseInt(key);
                if (sl >= this.linhkien.getSoluong()) {
                    txt_soluong.setText("");
                    txt_soluong.setText(String.valueOf(this.linhkien.getSoluong()));
                }
            } catch (NumberFormatException e) {
            }

        } else {
            txt_soluong.setEditable(false);
            txt_soluong.setText("1");
            lb_thongbao.setText("Không nhập chữ");
        }
    }//GEN-LAST:event_txt_soluongKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int sl = Integer.parseInt(txt_soluong.getText());
        if (sl < this.linhkien.getSoluong()) {
            sl++;
            txt_soluong.setText(String.valueOf(sl));
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int sl = Integer.parseInt(txt_soluong.getText().toString());
        if (sl == 1) {
            txt_soluong.setText(String.valueOf(sl));
        } else {
            sl--;
            txt_soluong.setText(String.valueOf(sl));
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_thongbao;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
