/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CT_hoadonDAO;
import entities.Hoadon;
import GUI.GuiControl.Tablemodelformhoadon;
import GUI.GuiControl.TablemodelCT_hoadon;
import entities.CT_hoadon;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author Ke Hien Le
 */
public class Formhoadon extends javax.swing.JFrame implements  Printable{

    private Hoadon hd;
    private double tiendua;
    private List<CT_hoadon> ds;
    Frame frame;
    public List<CT_hoadon> getDs() {
        return ds;
    }

    public void setDs(List<CT_hoadon> ds) {
        this.ds = ds;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public double getTiendua() {
        return tiendua;
    }

    public void setTiendua(double tiendua) {
        this.tiendua = tiendua;
    }

    public Hoadon getHd() {
        return hd;
    }

    public void setHd(Hoadon hd) {
        this.hd= hd;
    }

    public void setthongtin() {
        jLabel106.setText(hd.getId());
        jLabel122.setText(hd.getNhanvien().getId());
        jLabel105.setText(hd.getNgaylap().toString());
        jLabel120.setText(hd.getKhachhang().getTen());
        Double re =hd.Tinhtien()-hd.tinhthue();
        jLabel116.setText(frame.formattien(re)+"Đồng");
        jLabel112.setText(frame.formattien(hd.tinhthue()) + "  Đồng");
        jLabel118.setText(frame.formattien(hd.Tinhtien()) + "  Đồng");


        jLabel113.setText(frame.formattien(this.tiendua)  + "  Đồng");
        jLabel114.setText(frame.formattien(this.tiendua - hd.Tinhtien())  + "  Đồng");

    }

    /**
     * Creates new form formdangnhap
     */
    public Formhoadon(Hoadon hd, Frame frame) {
           this.hd= frame.getHd();
        initComponents();
     
        this.frame= frame;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel103 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 51, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("In hoá đơn");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 730, 108, 50));

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(0, 51, 153));
        jLabel101.setText("HD:");
        jPanel1.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 51));

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 51, 153));
        jLabel102.setText("Khách hàng");
        jPanel1.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 51));

        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(0, 51, 153));
        jLabel104.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");
        jPanel1.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 420, 40));

        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(0, 51, 153));
        jLabel105.setText("Hóa đơn bán hàng");
        jPanel1.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, 51));

        jLabel106.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(0, 51, 153));
        jLabel106.setText("Hóa đơn bán hàng");
        jPanel1.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 180, 51));

        jLabel115.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(0, 51, 153));
        jLabel115.setText("Hóa đơn bán hàng");
        jPanel1.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 289, 51));

        jTable1.setModel(new TablemodelCT_hoadon(hd.getId())
        );
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 530, 270));

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(0, 51, 153));
        jLabel103.setText("Ngày bán");
        jPanel1.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 51));

        jLabel107.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 51, 153));
        jLabel107.setText("Tiền khách trả");
        jPanel1.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 190, 51));

        jLabel109.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(0, 51, 153));
        jLabel109.setText("Số tiền phải thanh toán");
        jPanel1.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 581, 280, 40));

        jLabel111.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(0, 51, 153));
        jLabel111.setText("Tổng tiền mặt hàng thanh toán");
        jPanel1.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 280, 51));

        jLabel112.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(0, 51, 153));
        jLabel112.setText("Ngày bán");
        jPanel1.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 541, 140, 40));

        jLabel113.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(0, 51, 153));
        jLabel113.setText("Ngày bán");
        jPanel1.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 140, 40));

        jLabel114.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(0, 51, 153));
        jLabel114.setText("Ngày bán");
        jPanel1.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 140, 40));

        jLabel116.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(0, 51, 153));
        jLabel116.setText("Ngày bán");
        jPanel1.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 51));

        jLabel117.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(0, 51, 153));
        jLabel117.setText("Tiền thuế");
        jPanel1.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 280, 51));

        jLabel118.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(0, 51, 153));
        jLabel118.setText("Ngày bán");
        jPanel1.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 140, 40));

        jLabel119.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 51, 153));
        jLabel119.setText("Tiền trả lại");
        jPanel1.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 140, 51));

        jLabel120.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(0, 51, 153));
        jLabel120.setText("Hóa đơn bán hàng");
        jPanel1.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 40));

        jLabel121.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(0, 51, 153));
        jLabel121.setText("NVBH:");
        jPanel1.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 60, 51));

        jLabel122.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(0, 51, 153));
        jLabel122.setText("Hóa đơn bán hàng");
        jPanel1.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
            System.out.println(hd.getDsCthd());
           this.dispose();
            in();
            frame.setEnabled(rootPaneCheckingEnabled);
           
    }//GEN-LAST:event_jButton5ActionPerformed
    public int print(Graphics g, PageFormat pf, int page) throws
            PrinterException {

        if (page > 0) {
            /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }

        /* User (0,0) is typically outside the imageable area, so we must
         * translate by the X and Y values in the PageFormat to avoid clipping
         */
        Graphics2D g2d = (Graphics2D) g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());

        /* Now we perform our rendering */
        // test//
        g.drawString("MÁY TÍNH COCC", 250, 100);
        g.drawString("12, Nguyễn Văn Bảo, Phường 4, Quận Gò Vấp, Thành Phố Hồ Chí Mính", 100, 120);
        g.drawString("Số điện thoại: 0378238204 ", 100, 140);
        g.drawLine(100, 160, 500, 160);
        g.drawString("HOÁ ĐƠN MUA HÀNG", 250, 180);
        g.drawString("Mã hoá đơn :", 100, 200);
        g.drawString(hd.getId(), 230, 200);
        g.drawString("Ngày tạo hoá đơn:", 100, 220);
        g.drawString(hd.getNgaylap().toString(), 230, 220);
        g.drawString("Nhân viên:", 100, 240);
        g.drawString(hd.getNhanvien().getTen(), 230, 240);
        g.drawLine(100, 260, 500, 260);
        g.drawString("Khách hàng", 100, 280);
        g.drawString(hd.getKhachhang().getTen(), 230, 280);
        g.drawString("Số điện thoại KH", 100, 300);
        g.drawString(hd.getKhachhang().getSdt(), 230, 300);
        g.drawString("Địa chỉ KH", 100, 320);
        g.drawString(hd.getKhachhang().getDiachi(), 230, 320);
        g.drawLine(100, 340, 500, 340);
        g.drawString("STT", 100, 360);
        g.drawString("Sản phẩm", 130, 360);
        g.drawString("Số lượng", 390, 360);
        g.drawString("Thành tiền", 450, 360);
        CT_hoadonDAO ct_dao = new CT_hoadonDAO(CT_hoadon.class);
        
        java.util.List<CT_hoadon> list_ct = ct_dao.getbyidhd(frame.getHd().getId());
        hd.setDsCthd(list_ct);
        int line = 360;
        int stt = 1;
        for (int i = 0; i < list_ct.size(); i++) {
            line += 20;
            g.drawString(String.valueOf(stt), 100, line);
            g.drawString(list_ct.get(i).getLinhkien().getTen(), 130, line);
            g.drawString(String.valueOf(list_ct.get(i).getSoluong()), 390, line);
            ///double thanhtien = list_ct.get(i).getLinhkien().getDongiagoc() * list_ct.get(i).getSoluong();
            g.drawString(String.valueOf(list_ct.get(i).tinhtien_chitiet()), 450, line);
            stt++;
        }
        line += 20;
        g.drawLine(100, line, 500, line);
        line += 20;
        g.drawString("Tổng tiền: ", 200, line);
        g.drawString(String.valueOf(hd.Tinhtien().toString()) + " ", 450, line);
        line += 20;
        g.drawString("Phải thanh toán:", 200, line);
        g.drawString(String.valueOf((hd.Tinhtien())).toString(), 450, line);
        line += 20;
        g.drawString("( đồng )", 450, line);
        line += 20;
        g.drawLine(100, line, 500, line);
        line += 20;
        g.drawString("Hoá đơn đã bao gồm thuế VAT", 190, line);

        /* tell the caller that this page is part of the printed document */
        return PAGE_EXISTS;
    }

    public void in() {
        PrinterJob job = PrinterJob.getPrinterJob();
     job.setPrintable(this);
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
                /* The job did not successfully complete */
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Formhoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
